### ISSUE TITLE
Units eval:  [miles]/[hours]/[sec] vs ([miles]/[hours])/[sec] 

### ISSUE THREAD

**Issue by Bob-May** [mgreminger/EngineeringPaper.xyz#188] opened 2023-06-09 03:36 UTC
My understanding is that the parentheses should not alter the evaluation for the subject units.  However they do.

See [linked](https://engineeringpaper.xyz/udu5koLQtGyiVMzKXvWJXv)

**Comment by mgreminger** [comment] 2023-06-09 16:32
Thanks for question and thanks for including a link to your sheet, that helps out a lot. Yes, nested fractions can be a little confusing in terms of order of operations. You're correct, typing a/b/c in a calculator means the same as a/(b*c) because of order of operations. However, when you type the / symbol in EngineeringPaper.xyz, a fraction bar is inserted which acts as a [grouping symbol](https://flexbooks.ck12.org/cbook/ck-12-basic-algebra-concepts/section/1.4/primary/lesson/algebraic-expressions-with-fraction-bars-bsc-alg/) (effectively, everything above and below the fraction bar are treated as though they are grouped in their own set of parenthesis).  Because of this, when you type a/b/c, you're effectively getting a/(b/c). Since the b/c is evaluated first, the time units are cancelling for a1. 

There are two ways to get the calculation to work as intended. The fastest way to type it is to type a/b*c and you'll end up with a/(b*c). You can do the nested fractions approach as well, but you need to make sure the top fraction is evaluated first by typing a/c and then using the arrow to get the cursor just to the right of a and then type /b. After doing this, you'll get (a/b)/c where the parenthesis are implied. This is effectively your a2, the parenthesis can be deleted for your a2 and it will still work the same. I've updated [your sheet](https://engineeringpaper.xyz/yDr3m8RQxtiBKYuCXdHeWf) to show these two methods. Desmos works the [same way](https://www.desmos.com/calculator/tgxe9n4alk).

Let me know if you have any additional questions.

**Comment by Bob-May** [comment] 2023-06-10 09:10
I don't remember grouping signals from elementary school, but that was a long time ago.

Regardless, this works as expected, and is perhaps easier to look at as well:  
<img width="213" alt="image" src="https://github.com/mgreminger/EngineeringPaper.xyz/assets/47577359/7bd594d6-bb2d-48c7-bc00-7e6aa0ce732a">

**Comment by mgreminger** [comment] 2023-06-16 12:54
Closing this issue as resolved, feel free to add additional comments to this issue if there are any further questions.

**Closed by mgreminger** 2023-06-16 12:54 UTC
